// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bcmp_snn_upper_edges_parallel_cpp
IntegerMatrix bcmp_snn_upper_edges_parallel_cpp(const IntegerMatrix nn_idx_k, const int min_shared);
RcppExport SEXP _bcmp_bcmp_snn_upper_edges_parallel_cpp(SEXP nn_idx_kSEXP, SEXP min_sharedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix >::type nn_idx_k(nn_idx_kSEXP);
    Rcpp::traits::input_parameter< const int >::type min_shared(min_sharedSEXP);
    rcpp_result_gen = Rcpp::wrap(bcmp_snn_upper_edges_parallel_cpp(nn_idx_k, min_shared));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bcmp_bcmp_snn_upper_edges_parallel_cpp", (DL_FUNC) &_bcmp_bcmp_snn_upper_edges_parallel_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_bcmp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
