# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bcmp_snn_upper_edges_parallel_cpp <- function(nn_idx_k, min_shared) {
    .Call(`_bcmp_bcmp_snn_upper_edges_parallel_cpp`, nn_idx_k, min_shared)
}
